app: aws-node
service: aws-node

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
iamRoleStatements:
  - Effect: "Allow"
    Action:
       - "s3:*"
    Resource:
       - { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ]]}
       - "arn:aws:s3:::example-folder/*"



functions:
  hola:
    handler: handler.hola

  apiExampleOrderCreate:
    handler: Api/examples/order.create
    package:
     include:
     - Utils/db/connection.js
    events:
      - http:
         path: order/create
         method: post
  
  ftpExampleOrderCreate:
    handler: FTP/examples/order.create
    events:
      - s3:
          bucket: example-folder1
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploads/
      - eventBridge:
          schedule: rate(10 minutes)
plugins: 
  - serverless-dotenv-plugin